# Site
name: "P2P Best Practices"
title: "P2P Best Practices"
description: "Welcome to this collection of best practices to build great sites for collaborative knowledge production"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: 'https://katoss.github.io'
google_analytics: ''
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kat:
    name: Katharina
    display_name: Katharina
    avatar: assets/images/avatar-kat.jpg
    email: katharina.kloppenborg@cri-paris.org
    web: https://peer-produced.science/team/
    twitter: https://twitter.com/k_kloppenborg
    description: "PhD student at CRI (Center for Research and Interdisciplinarity) in Paris, experimenting with a user-centered approach to support the peer-production of knowledge in citizen science."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
